modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yclib"
version = "${version}"
displayName = "YCLib"
authors = "YukkuriC"
description = '''

'''
#logoFile = ""

[[dependencies.yclib]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yclib]]
modId = "minecraft"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
