modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yclib"
version = "${version}"
displayName = "YCLib"
authors = "YukkuriC"
description = '''

'''
#logoFile = ""

[[dependencies.yclib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yclib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "yclib.mixins.forge.json"
